package com.surendra.oauth.server.constant;

public enum OAuthConstants {
    OAUTH_CLIENT_CREATED,
    OAUTH_CREDENTIALS_DOWNLOADED,
    OAUTH_CLIENT_DELETED,
    OAUTH_CLIENT_LIST_LOADED,
    OAUTH_ACCESS_TOKEN_REQUESTED,
    OAUTH_ACCESS_TOKEN_REQUEST_SUCCEEDED,
    OAUTH_ACCESS_TOKEN_REQUEST_ACCESS_DENIED,
    OAUTH_ACCESS_TOKEN_REQUEST_FAILED
}
