#!/bin/bash

# This file will create a new settings.xml file containing the variables set for a Maven username and password.

#echo $BASH_SOURCE
#echo `pwd`
DIR=`pwd`
TEMPLATE_FILE=$DIR/scripts/maven/settings.template.xml
DEST_FILE_NAME=settings.xml
DESTINATION_FILE=$DIR/$DEST_FILE_NAME
GITIGNORE=$DIR/.gitignore

echo "Checking for presence of MYGET_REPO_USERNAME environment variable..."
if [[ -z $MYGET_REPO_USERNAME ]]; then
  >&2 echo "Error: MYGET_REPO_USERNAME environment variable not set.  Please set this environment variable and try again."
  exit 1
fi;

echo "Checking for presence of MYGET_REPO_PASSWORD environment variable..."
if [[ -z $MYGET_REPO_PASSWORD ]]; then
  >&2 echo "Error: MYGETN_REPO_PASSWORD environment variable not set.  Please set this environment variable and try again."
  exit 2
fi;

echo "Creating $DESTINATION_FILE file..."

if [ -f $TEMPLATE_FILE ]; then
   if cat $TEMPLATE_FILE | sed  "s/%MYGET_REPO_USERNAME%/$MYGET_REPO_USERNAME/g"  | sed "s/%MYGET_REPO_PASSWORD%/$MYGET_REPO_PASSWORD/g" | sed "s/generation text/ATTENTION: This file was generated by the create-settings.sh script. Do not commit it to version control as it contains credentials!/" > $DESTINATION_FILE; then
      if ! grep -q "^$DEST_FILE_NAME$" $GITIGNORE; then
         echo "Warning: $DEST_FILE_NAME not found in $GITIGNORE file.  Add $DEST_FILE_NAME to $GITIGNORE to ensure you don't accidently commit your credentials!"
      fi

      echo "Success - $DESTINATION_FILE file successfully created."
      exit 0;
   else
      >&2 echo "Failure - There was an error creating the $DESTINATION_FILE file.";
      exit 3;
   fi;
else
   >&2 echo "Failure - $TEMPLATE_FILE does not exist.";
   exit 4;
fi;
